---
driver:
  name: podman

log: true

platforms:
  - name: ubi8
    hostname: ubi8
    image: ubi8/ubi-init
    registry:
      url: registry.access.redhat.com
    dockerfile: Dockerfile
    pkg_extras: python*setuptools
    volumes:
      - /etc/ci/mirror_info.sh:/etc/ci/mirror_info.sh:ro
      - /etc/pki/rpm-gpg:/etc/pki/rpm-gpg
      - /opt/yum.repos.d:/etc/yum.repos.d:rw
    privileged: true
    environment: &env
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"
    ulimits: &ulimit
      - host

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          ubi8:
            ansible_python_interpreter: /usr/bin/python3
        children:
          allovercloud:
            hosts:
              ubi8:
                ctlplane_ip: 10.0.0.1
                ctlplane_hostname: ubi8.ctlplane.localdomain
                internal_api_ip: 10.0.1.1
                internal_api_hostname: ubi8.internalapi.localdomain
                management_ip: 10.0.0.1  # no management_hostname
                canonical_hostname: ubi8.localdomain
                tripleo_role_networks: [ctlplane, internal_api, management]
  log: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - verify
    - destroy

lint:
  enabled: false

verifier:
  name: testinfra
  lint:
    name: flake8
