---
dependency:
  name: galaxy
  options:
    role-file: molecule/common/requirements.yml
driver:
  name: podman

platforms:
  - name: collectd-test
    hostname: collectd-test
    image: centos/centos:stream8
    registry:
      url: quay.io
    pkg_extras: python*setuptools libselinux-python* policycoreutils-python-utils
    volumes:
      - /etc/ci/mirror_info.sh:/etc/ci/mirror_info.sh:ro
      # Had to comment this out or I get "No URLs in mirrorlist"
      #- /etc/dnf/vars:/etc/dnf/vars
    privileged: true
    environment: &env
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"
      CONTAINER_BIN: podman
    ulimits: &ulimit
      - host
    docker_networks:
      - name: collectd
        ipam_config:
          - subnet: "192.168.42.0/24"
            gateway: "192.168.42.254"
    networks:
      - name: collectd
        ipv4_address: "192.168.42.1"
  - name: collectd-server
    hostname: collectd-server
    image: centos/centos:stream8
    registry:
      url: quay.io
    pkg_extras: python*setuptools libselinux-python* policycoreutils-python-utils
    volumes:
      - /etc/ci/mirror_info.sh:/etc/ci/mirror_info.sh:ro
    privileged: true
    environment:
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"
      CONTAINER_BIN: podman
    ulimits:
      - host
    networks:
      - name: collectd
        ipv4_address: "192.168.42.2"

provisioner:
  inventory:
    hosts:
      all:
        hosts:
          collectd-test:
            ansible_python_interpreter: /usr/bin/python3
    host_vars:
      collectd-test:
        collectd_conf_output_dir: "/etc/collectd.d/"
  name: ansible
  log: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
    ANSIBLE_FILTER_PLUGINS: "${ANSIBLE_FILTER_PLUGINS:-\
                              /usr/share/ansible/plugins/filter}"
  playbooks:
    prepare: ../common/prepare.yml

verifier:
  name: ansible

scenario:
  test_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy
    - cleanup
