---
driver:
  name: delegated
  options:
    managed: false
    login_cmd_template: >-
      ssh
      -o UserKnownHostsFile=/dev/null
      -o StrictHostKeyChecking=no
      -o Compression=no
      -o TCPKeepAlive=yes
      -o VerifyHostKeyDNS=no
      -o ForwardX11=no
      -o ForwardAgent=no
      {instance}
    ansible_connection_options:
      ansible_connection: ssh

log: true

platforms:
  - name: controller1
  - name: controller2

provisioner:
  name: ansible
  config_options:
    defaults:
      fact_caching: jsonfile
      fact_caching_connection: /tmp/molecule/facts
  inventory:
    hosts:
      all:
        hosts:
          controller1:
            ansible_host: 127.0.0.2
          controller2:
            ansible_host: 127.0.0.3
  log: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml

scenario:
  test_sequence:
    - converge

verifier:
  name: testinfra
