---
driver:
  name: podman

log: true

platforms:
  - name: overcloud-controller-0
    hostname: overcloud-controller-0
    image: centos:7
    dockerfile: Dockerfile
    pkg_extras: python-setuptools
    easy_install:
      - pip
    environment: &env
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - ALL  # CENT7 requires all due to the age of the software
    volumes:
      - /run/udev:/run/udev:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/ci/mirror_info.sh:/etc/ci/mirror_info.sh:ro

  - name: overcloud-controller-1
    hostname: overcloud-controller-1
    image: centos:7
    dockerfile: Dockerfile
    pkg_extras: python-setuptools
    easy_install:
      - pip
    environment:
      <<: *env
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - ALL  # CENT7 requires all due to the age of the software
    volumes:
      - /run/udev:/run/udev:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/ci/mirror_info.sh:/etc/ci/mirror_info.sh:ro

provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy

lint:
  enabled: false

verifier:
  name: testinfra
  lint:
    name: flake8
