---
# Copyright 2019 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- hosts: localhost
  connection: local
  tasks:

    - name: Build keystone container
      shell: docker build -t keystone-img -f Dockerfile.keystone .

    - name: Run keystone container
      shell: docker run -d -p 5000:5000 --name keystone-docker keystone-img

- name: Prepare
  hosts: all
  tasks:

    - include_role:
        name: test_deps
      vars:
        test_deps_setup_tripleo: true

    - name: Instal pre packages
      package:
        name:
          - python-setuptools
          - python-openstacksdk
          - python-openstackclient
          - python-keystoneclient
          - ansible
