---
driver:
  name: podman

log: true

platforms:
  - name: centos8
    hostname: centos8
    image: centos:8
    dockerfile: Dockerfile
    pkg_extras: python*-setuptools
    environment:
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"
    command: /sbin/init
    capabilities:
      - ALL
    volumes:
      - /dev:/dev
      - /lib/modules:/lib/modules
      - /etc/ci/mirror_info.sh:/etc/ci/mirror_info.sh:ro
    privileged: true
    ulimits:
      - host

provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
