---

- name: Set node name fact
  set_fact:
    node_hostname: "{{ canonical_hostname }}"

- include_tasks: certificate.yml
  when:
    - private_key_content|length > 0
    - ca_cert_content|length > 0
    - service_pem_content|length > 0

- include_tasks: netport.yml
- include_tasks: netinterface.yml
- include_tasks: octavia.yml
