---
- job:
    description: Base tripleo-ansible job on CentOS 8
    name: tripleo-ansible-centos-8-base
    nodeset: centos-8-stream
    parent: base
    success-url: "reports.html"
    failure-url: "reports.html"
    pre-run:
    - tripleo_ansible/playbooks/prepare-test-host.yml
    - zuul.d/playbooks/pre.yml
    run:
    - zuul.d/playbooks/run.yml
    timeout: 3600
    voting: true
