---
driver:
  name: podman

log: true

platforms:
  - name: centos8
    hostname: centos8
    image: centos:8
    dockerfile: Dockerfile
    pkg_extras: python*-setuptools
    environment:
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"
    ulimits:
      - host
    command: /sbin/init
    privileged: true
    capabilities:
      - ALL
    volumes:
      - /run/udev:/run/udev:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /lib/modules:/lib/modules
      - /etc/ci/mirror_info.sh:/etc/ci/mirror_info.sh:ro

provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
    ANSIBLE_ROLES_PATH: "${ANSIBLE_ROLES_PATH}:${HOME}/zuul-jobs/roles"
    ANSIBLE_LIBRARY: "${ANSIBLE_LIBRARY}:/usr/share/ansible/plugins/modules"
    ANSIBLE_FILTER_PLUGINS: "${ANSIBLE_FILTER_PLUGINS}:/usr/share/ansible/plugins/filter"

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
