---
driver:
  name: docker

log: true

platforms:
  - name: centos7
    hostname: centos7
    image: centos:7
    dockerfile: Dockerfile
    pkg_extras: python-setuptools
    easy_install:
      - pip
    environment: &env
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"
    command: >-
      /sbin/init &&
      /bin/mkdir -p /var/run/dbus &&
      /usr/bin/dbus-uuidgen > /var/lib/dbus/machine-id &&
      /usr/bin/dbus-daemon --config-file=/usr/share/dbus-1/system.conf
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - ALL
    volumes:
      - /dev:/dev
      - /lib/modules:/lib/modules
      - /etc/ci/mirror_info.sh:/etc/ci/mirror_info.sh:ro

# TODO(cloudnull): when RDO has centos8 repos this test node should be re-enabled.
#
#  - name: centos8
#    hostname: centos8
#    image: centos:8
#    dockerfile: Dockerfile
#    pkg_extras: python*-setuptools
#    environment:
#      http_proxy: "{{ lookup('env', 'http_proxy') }}"
#      https_proxy: "{{ lookup('env', 'https_proxy') }}"
#    command: >-
#      /sbin/init &&
#      /bin/mkdir -p /var/run/dbus &&
#      /usr/bin/dbus-uuidgen > /var/lib/dbus/machine-id &&
#      /usr/bin/dbus-daemon --config-file=/usr/share/dbus-1/system.conf
#    privileged: true
#    tmpfs:
#      - /run
#      - /tmp
#    capabilities:
#      - ALL
#    volumes:
#      - /dev:/dev
#      - /lib/modules:/lib/modules

provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
    ANSIBLE_ROLES_PATH: "${ANSIBLE_ROLES_PATH:-/usr/share/ansible/roles}:${HOME}/zuul-jobs/roles"
    ANSIBLE_LIBRARY: "${ANSIBLE_LIBRARY:-/usr/share/ansible/plugins/modules}"
    ANSIBLE_FILTER_PLUGINS: "${ANSIBLE_FILTER_PLUGINS:-/usr/share/ansible/plugins/filter}"
    ANSIBLE_ACTION_PLUGINS: "${ANSIBLE_ACTION_PLUGINS:-/usr/share/ansible/plugins/action}"

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy

lint:
  enabled: false

verifier:
  name: testinfra
  lint:
    name: flake8
