---
driver:
  name: docker

log: true

platforms:
  - name: centos7
    hostname: centos7
    image: centos:7
    dockerfile: Dockerfile
    pkg_extras: python-setuptools
    volumes:
      - /etc/ci/mirror_info.sh:/etc/ci/mirror_info.sh:ro
    easy_install:
      - pip
    environment: &env
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"

  - name: centos8
    hostname: centos8
    image: centos:8
    dockerfile: Dockerfile
    pkg_extras: python*-setuptools
    volumes:
      - /etc/ci/mirror_info.sh:/etc/ci/mirror_info.sh:ro
    environment:
      <<: *env

provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
  inventory:
    hosts:
      all:
        vars:
          # use a tmp hosts path since /etc/hosts isn't writeable in the
          # molecule test containers
          tripleo_hosts_entries_hosts_path: /tmp/hosts
          tripleo_hosts_entries_undercloud_hosts_entries: []
          tripleo_hosts_entries_extra_hosts_entries: []
          tripleo_hosts_entries_vip_hosts_entries: []
          cloud_domain: localdomain
          role_networks:
            - ctlplane
            - InternalApi
          networks:
            ctlplane:
              name_lower: ctlplane
            InternalApi:
              name_lower: internal_api
        children:
          overcloud:
            hosts:
              centos8:
                hostname_resolve_network: ctlplane
                ctlplane_ip: 192.168.24.1
                internal_api_ip: 172.17.0.1
              centos7:
                hostname_resolve_network: ctlplane
                ctlplane_ip: 192.168.24.2
                internal_api_ip: 172.17.0.2


scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy

lint:
  enabled: false

verifier:
  name: ansible
  lint:
    name: ansible-lint
